FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc default-libmysqlclient-dev pkg-config
RUN pip install flask flask-login werkzeug pymysql flask-sqlalchemy cryptography gunicorn
